name: flutter_avif_web
description: Web implementation for flutter_avif.
version: 2.5.0
repository: https://github.com/yekeskin/flutter_avif/tree/main/flutter_avif_web

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_avif_platform_interface:
    path: ../flutter_avif_platform_interface
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter:
  plugin:
    implements: flutter_avif
    platforms:
      web:
        pluginClass: FlutterAvifWeb
        fileName: flutter_avif_web.dart
