name: Build Android

on:
  workflow_dispatch:
      dry_run:
        description: Dry run, do NOT upload artifacts.
        required: true
        type: boolean
        default: true

env:
  CI_RUST_VERSION: '1.83.0'

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - run: |
          sudo apt update -y
          sudo apt install -y ninja-build
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{env.CI_RUST_VERSION}}
          targets: aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android,i686-linux-android
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28
      - name: Update NDK path
        run: |
          echo "${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH
      - name: Build
        run: |
          sudo apt install -y make meson nasm
          cargo install cargo-ndk@3.5.4 --locked
          ./scripts/build-flutter_avif-android.sh
      - name: Upload Android libts
        if: ${{ !inputs.dry_run }}
        uses: actions/upload-artifact@v4
        with:
          name: jniLibs
          path: |
            flutter_avif_android/android/src/main/jniLibs/arm64-v8a/libflutter_avif.so
            flutter_avif_android/android/src/main/jniLibs/x86_64/libflutter_avif.so
